<?php
/*
 * APIMATICCalculatorLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 07/28/2016
 */

namespace APIMATICCalculatorLib\Models;

/**
 * Possible operators are sum, subtract, multiply, divide
 */
class OperationTypeEnum {
    /**
     * Represents the sum operator
     */
    const SUM = "SUM";

    /**
     * Represents the subtract operator
     */
    const SUBTRACT = "SUBTRACT";

    /**
     * Represents the multiply operator
     */
    const MULTIPLY = "MULTIPLY";

    /**
     * Represents the divide operator
     */
    const DIVIDE = "DIVIDE";

}